schema_version: 1

context:
  version: "0.6.0"

package:
  name: geolibre-wasm
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/g/geolibre-wasm/geolibre_wasm-${{ version }}.tar.gz
  sha256: 8e52f2368026845a8e12bc6f618daa6cc2dfb188a5f53a5c6f1e734bf9f3a92f

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - wasmtime-py >=20,<50

tests:
  - python:
      imports:
        - geolibre_wasm
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://github.com/opengeos/geolibre-rust
  summary: Run the GeoLibre / whitebox_next_gen geospatial tool suite (WASM/WASI) from Python.
  description: GeoLibre is a geospatial tool suite that provides a Python interface to the GeoLibre / whitebox_next_gen geospatial tool suite.
  license: MIT
  license_file: LICENSE
  repository: https://github.com/opengeos/geolibre-rust

extra:
  recipe-maintainers:
    - giswqs
